name: chatting_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  achievement_view: ^1.0.1
  loading_indicator: ^3.1.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  emoji_picker_flutter: ^3.1.0
  supabase_flutter: ^2.8.3
  lottie: ^3.3.0
  page: ^1.2.2
  transition: ^2.0.2
  page_transition: ^2.2.1
  photo_view: ^0.15.0
  hooks_riverpod: ^2.6.1
  chewie: ^1.10.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/wechat.png"
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/images/wechat.png" 

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
 