// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBbgKgg_dTx99rnfwfxuiG9UFfTAD9Y0',
    appId: '1:683837441240:web:caed789c1e03be4ba483ad',
    messagingSenderId: '683837441240',
    projectId: 'we-chat--0',
    authDomain: 'we-chat--0.firebaseapp.com',
    storageBucket: 'we-chat--0.appspot.com',
    measurementId: 'G-6DBZ60E1KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCHBVZUw5BcGpyyvxsB2iCp_S5zJT9BU',
    appId: '1:767902581735:android:750cff6d98be151155f342',
    messagingSenderId: '767902581735',
    projectId: 'we-chat-ed40a',
    storageBucket: 'we-chat-ed40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1BHMnT6F_xcY4OCxX0IBPllPW_vVY20',
    appId: '1:683837441240:ios:6511a52cacb979c2a483ad',
    messagingSenderId: '683837441240',
    projectId: 'we-chat--0',
    storageBucket: 'we-chat--0.appspot.com',
    androidClientId: '683837441240-8bv3aunb9tomgbg6a1huo8fbtovj08kj.apps.googleusercontent.com',
    iosClientId: '683837441240-cafm5ad81ckhpboq2ksr1hbg22n0u4lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1BHMnT6F_xcY4OCxX0IBPllPW_vVY20',
    appId: '1:683837441240:ios:6511a52cacb979c2a483ad',
    messagingSenderId: '683837441240',
    projectId: 'we-chat--0',
    storageBucket: 'we-chat--0.appspot.com',
    androidClientId: '683837441240-8bv3aunb9tomgbg6a1huo8fbtovj08kj.apps.googleusercontent.com',
    iosClientId: '683837441240-cafm5ad81ckhpboq2ksr1hbg22n0u4lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxBbgKgg_dTx99rnfwfxuiG9UFfTAD9Y0',
    appId: '1:683837441240:web:e720961695a9e78fa483ad',
    messagingSenderId: '683837441240',
    projectId: 'we-chat--0',
    authDomain: 'we-chat--0.firebaseapp.com',
    storageBucket: 'we-chat--0.appspot.com',
    measurementId: 'G-N12SL8HGE6',
  );

}